{{- with .Values.ingressRoute }}
{{- if .enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
spec:
  secretName: grafana-tls
  dnsNames:
    - {{ .host }}
  issuerRef:
    name: {{ .issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
