apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-certs
  labels:
    app.kubernetes.io/name: step-ca
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  root_ca.crt: |-
{{ .Files.Get "files/root_ca.crt" | indent 4 }}
  intermediate_ca.crt: |-
{{ .Files.Get "files/intermediate_ca.crt" | indent 4 }}
