apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-config
  labels:
    app.kubernetes.io/name: step-ca
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ca.json: |-
{{ .Files.Get "files/ca.json" | indent 4 }}
