apiVersion: v2
name: prometheus
description: Prometheus metrics store for the workstation platform
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 29.18.0
