"""Environment preflight checks for the workstation bootstrap.

Verifies that the host and required tooling are in a state where the imperative seed can run and
hand off to ArgoCD. Checks are classified as required (a failure blocks bootstrap) or advisory
(a failure is reported as a warning only).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from . import console, tools


class Status(Enum):
    OK = "ok"
    WARN = "warn"
    FAIL = "fail"


@dataclass(frozen=True)
class CheckResult:
    name: str
    status: Status
    detail: str


# Tools installed by the bootstrap when missing (see tools.py). k3s is installed by its own phase.
_MANAGED_TOOLS = ("kubectl", "helm", "sops", "age", "step", "k3s")


def _check_tools() -> list[CheckResult]:
    results: list[CheckResult] = []
    for tool in _MANAGED_TOOLS:
        if shutil.which(tool) is None:
            results.append(
                CheckResult(f"tool:{tool}", Status.WARN, "missing (installed by bootstrap)")
            )
        else:
            version = tools.installed_version(tool) or "present"
            results.append(CheckResult(f"tool:{tool}", Status.OK, version))
    return results


def _check_wsl() -> CheckResult:
    proc_version = Path("/proc/version")
    text = proc_version.read_text() if proc_version.exists() else ""
    if "microsoft" in text.lower() or os.environ.get("WSL_DISTRO_NAME"):
        return CheckResult("host:wsl2", Status.OK, os.environ.get("WSL_DISTRO_NAME", "detected"))
    return CheckResult("host:wsl2", Status.WARN, "not running under WSL2 (design target is WSL2)")


def _check_systemd() -> CheckResult:
    if Path("/run/systemd/system").exists():
        return CheckResult("host:systemd", Status.OK, "running")
    return CheckResult(
        "host:systemd",
        Status.FAIL,
        "systemd not active (enable systemd in wsl.conf; k3s requires it)",
    )


def _check_gpu() -> CheckResult:
    if shutil.which("nvidia-smi") is None:
        return CheckResult("gpu:nvidia", Status.WARN, "nvidia-smi not found (needed for AI layer)")
    try:
        proc = subprocess.run(  # noqa: S603 - fixed, trusted tool name
            ["nvidia-smi", "-L"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return CheckResult("gpu:nvidia", Status.WARN, f"nvidia-smi failed: {exc}")
    listing = proc.stdout.strip()
    if proc.returncode != 0 or not listing:
        return CheckResult("gpu:nvidia", Status.WARN, "no GPU reported by nvidia-smi")
    return CheckResult("gpu:nvidia", Status.OK, listing.splitlines()[0])


def _check_age_key() -> CheckResult:
    key_path = os.environ.get("SOPS_AGE_KEY_FILE")
    candidates = [Path(key_path)] if key_path else []
    candidates.append(Path.home() / ".config" / "sops" / "age" / "keys.txt")
    for candidate in candidates:
        if candidate.exists():
            return CheckResult("secrets:age-key", Status.OK, str(candidate))
    return CheckResult(
        "secrets:age-key",
        Status.WARN,
        "missing (generated by bootstrap)",
    )


def collect() -> list[CheckResult]:
    """Run all preflight checks and return their results."""
    results: list[CheckResult] = []
    results.extend(_check_tools())
    results.append(_check_wsl())
    results.append(_check_systemd())
    results.append(_check_gpu())
    results.append(_check_age_key())
    return results


def report(results: list[CheckResult]) -> None:
    for result in results:
        line = f"{result.name}: {result.detail}"
        if result.status is Status.OK:
            console.ok(line)
        elif result.status is Status.WARN:
            console.warn(line)
        else:
            console.error(line)


def run(strict: bool = False) -> bool:
    """Run preflight and return True when the environment is acceptable.

    When strict is True, advisory warnings are treated as failures.
    """
    console.step("Running preflight checks")
    results = collect()
    report(results)

    has_fail = any(r.status is Status.FAIL for r in results)
    has_warn = any(r.status is Status.WARN for r in results)

    if has_fail:
        console.error("Preflight failed: resolve the errors above before bootstrapping")
        return False
    if strict and has_warn:
        console.error("Preflight failed in strict mode: resolve the warnings above")
        return False
    if has_warn:
        console.warn("Preflight passed with warnings")
    else:
        console.ok("Preflight passed")
    return True
