apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: workstation
  source:
    repoURL: https://github.com/forterro/k3s-workstation-platform.git
    targetRevision: main
    path: umbrella-charts/kube-mgmt/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
