apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: workstation
  source:
    repoURL: https://github.com/forterro/k3s-workstation-platform.git
    targetRevision: main
    path: umbrella-charts/observability/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
